const Erros = {
  DESCONHECIDO: "DESCONHECIDO",
  EMAIL_INVALIDO: "EMAIL_INVALIDO",
  NOME_PEQUENO: "NOME_PEQUENO",
  ID_INVALIDO: "ID_INVALIDO",
  NOME_VAZIO: "NOME_VAZIO",
  NOME_GRANDE: "NOME_GRANDE",
  NOME_SEM_SOBRENOME: "NOME_SEM_SOBRENOME",
  NOME_CARACTERES_INVALIDOS: "NOME_CARACTERES_INVALIDOS"
} as const;

export default Erros;
